### ISSUE TITLE
Manifestoless Manifesto

### ISSUE THREAD

**Issue by lele85** [frameworkless-movement/manifesto#1]
Where is the manifesto? Is it manifestoless? :D

**Comment by francesco-strazzullo** [comment]
Very good question indeed. We are going to create a manifesto in the next weeks, we are currently working on that.

We opened the empty repo just to show it during a talk at [WEBdeLDN](http://webdeldn.rocks/) about Frameworkless Development.

We used this empty repo to start asking for some kind of interest, open an issue asking information, putting a star on it, these kinds of things.

I know this is not a common practice, but it was for the _sake of the show_ ;)

**Comment by francesco-strazzullo** [comment]
Hi @lele85 we released the first draft of our principles.

**Comment by apiraino** [comment]
Hi,

a couple of questions that came up after reading the draft:

* define scope of the proposal
* pinpoint the problems of excessive relying on a framework
* maybe examples of bad framework usage (and why) and provide an alternate approach (based on your experience)
* from the manifesto: `[frameworks] are the most powerful tool to learn how to code without them` not sure about the meaning of this.
* perhaps clarify a bit more what frameworkless is *not* (build your own library? reinvent the wheel? NIH? etc.)

cheers :beer:

**Comment by francesco-strazzullo** [comment]
@apiraino If you're ok with it, I will open a separate Issue for every point. It will be easier to track down discussions. What do you think?
