### ISSUE TITLE
about `lack of knowledge regarding technical debt`

### ISSUE THREAD

**Issue by sensorario** [frameworkless-movement/manifesto#14]
Is in the purpose of this movement suggest some libraries or component? If yes, ... could be present here at least name of good patterns to use? Or libraries? Or part of frameworks.

**Comment by francesco-strazzullo** [comment]
One the purpose of the movement is to help others to learn. So yes we are going to add some resources about how to write without frameworks or how to use a framework in a "frameworkless" way.

But for me, it's not a good idea to add this material in this repository. I mean that, as a manifesto, this should be as much as universal as possible. So in this repo, we can't just say "use Reactive programming" or something like that.

One possible solution is to create another repo to add resources, categorized by language or kind of problems that someone has to solve.

With resource, I mean something like posts, videos or repos with code examples.
