### ISSUE TITLE
How to sign the manifesto?

### ISSUE THREAD

**Issue by gimmi** [frameworkless-movement/manifesto#16]

**Comment by francesco-strazzullo** [comment]
Hi @gimmi, 
We don't have a manifesto yet. We're still working on it. But if you're interested in the Frameworkless Movement you can and you want to help us you can:

1. Add a star to this repo
2. Help us spread the word on social media about the movement

We want to create this manifesto sharing our ideas with other developers, so right now we're creating a distributed team to help us to create a good Manifesto. If you want to be part of this team please send an email to info@frameworklessmovement.org.

**Comment by francesco-strazzullo** [comment]
@gimmi I've added this info to the the README with the PR #18

**Comment by gimmi** [comment]
Hi @francesco-strazzullo 

- [x] Add a star to this repo
- [ ] Help us spread the word on social media about <= WIP

Thanks a lot!
