### ISSUE TITLE
Visual Identity 

### ISSUE THREAD

**Issue by mfeitoza** [frameworkless-movement/manifesto#17]
Hi everyone,

any plans for visual identity of manifesto?

**Comment by adellava** [comment]
Yes, we already started to work on the manifesto visual identity. A visual identity kit will be available on this repo in few weeks.

**Comment by francesco-strazzullo** [comment]
@mfeitoza we just added the logo on the organization and on the Readme. @adellava is working on a visual identity kit.

**Comment by adellava** [comment]
@mfeitoza you can find here our start, https://github.com/frameworkless-movement/frameworkless-visual-identity feel free to contribute
