### ISSUE TITLE
"abuse of the use of frameworks"

### ISSUE THREAD

**Issue by francesco-strazzullo** [frameworkless-movement/manifesto#20]
Taking a look here https://dictionary.cambridge.org/dictionary/english/abuse, it seems that abuse it's a too strong word.

The main meaning of abuse is 

> to use something for the wrong purpose in a way that is harmful or morally wrong

I don't think that this is the meaning that we want to pass, what do you think?

**Comment by GeoDoo** [comment]
I think misuse or wrong use of frameworks would better convey the meaning you want to express here!

https://dictionary.cambridge.org/dictionary/english/misuse

and the syntax is wrong: when you say abuse you should not use use again! haha

So, the full sentence would be like:

the misuse of frameworks or the wrong use of frameworks

:)

**Comment by ggeorgovassilis** [comment]
@francesco-strazzullo I agree that aggressive or diminishing wording should be avoided if we indeed feel that way. Peoples' individual stories may vary, so here is mine: I would subscribe, cautiously, to the meaning you quoted because I've seen once too many "gurus" push frameworks to solidify their own position in a project where something simpler would have done fine. To me, that is an abuse of power in a project.

**Comment by francesco-strazzullo** [comment]
@ggeorgovassilis I think that you may have a point. But I think that we are talking about politics and organization design here, more than decision making. For now, I think we should change the work in "misuse" or another similar word. I would like to talk about "Organizations" in a separate issue if you are ok with it.

**Comment by francesco-strazzullo** [comment]
@lorenzomassacci @Violo @adellava What do you think about the proposal of @GeoDoo?

**Comment by adellava** [comment]
The @GeoDoo proposal makes sense. Let's go for `misuse`.

**Comment by francesco-strazzullo** [comment]
Ok then, I will open a PR later with the fix!

**Comment by lorenzomassacci** [comment]
I'm not sure `misuse` is better than `abuse`. With the word abuse I mean an **excessive use** of frameworks not only a _wrong use_. Something like _drug abuse_  or _alcohol abuse_

**Comment by francesco-strazzullo** [comment]
I like the analogy with drugs. I found this post about the difference between abuse and misuse. https://newlifehouse.com/drug-abuse-vs-misuse/

**Comment by GeoDoo** [comment]
After reading the article of @francesco-strazzullo I would go with `misuse` for the only reason that you cannot get addicted to Frameworks.... hahahaha

I think... Although JS community should use the help of a psychiatrist... to stop the JS fatigue

hahaha

**Comment by francesco-strazzullo** [comment]
Quoting the post:

> Misuse involves not following medical instructions, but the person may not necessarily be looking to ‘get high’ from their use

on the other hand...

> Not only do they use it in a way other than it is prescribed, but they also use it to experience the feelings associated with the drug

At the hand of the post, they say 

> According to the FDA (Food and Drug Administration) the key difference between drug abuse and drug misuse is the individual’s intentions when taking the drug.

I agree with you @lorenzomassacci that abuse, when associated with drugs, means *excessive use* but the focus is on the intention of the team.

I think that the message of that paragraph is related to the _[law of the instrument](https://en.wikipedia.org/wiki/Law_of_the_instrument)_ that states that

> "I suppose it is tempting, if the only tool you have is a hammer, to treat everything as if it were a nail."

That said I don't think that people actually intend to use "too much" of a framework on purpose.

**Comment by GeoDoo** [comment]
About the excessive use, I agree that @lorenzomassacci has a point, but if you look it individually *one* company should be abusing frameworks if and only if it changes frameworks like shirts! 

If you are talking in general then the analogous would be to say that the humanity abuses alcohol... Which I do not think it is what you want to say here... I am not sure if you can say that the community is a drag addict... Only individuals can get addicted in a strict sense of the meaning... I think

What say you?
