### ISSUE TITLE
"make deliberate tech decisions."

### ISSUE THREAD

**Issue by francesco-strazzullo** [frameworkless-movement/manifesto#21]
I'm thinking about the word deliberate when talking about tech decisions. Taking a look at the [dictionary](https://dictionary.cambridge.org/dictionary/english/deliberate) the word deliberate means:

> (often of something bad) intentional or planned

or

> A deliberate movement, action, or thought is done carefully without hurrying

I think that in this case, it's better to use `aware` or `conscious`. The point is to make decisions considering the natural tradeoff of every decision.

What do you think?

**Comment by GeoDoo** [comment]
hey @francesco-strazzullo I read the whole paragraph! There are some minor syntactical errors too.

If i got the meaning correctly you want to say help people make meaningful decisions. You want the decision someone makes to have a meaning, a significato, some importance not just choose randomly, right?

check these phrases here: https://www.wordreference.com/EnglishCollocations/meaningful 

https://www.wordreference.com/EnglishCollocations/importance

**Comment by francesco-strazzullo** [comment]
@GeoDoo it's not just about a meaning. It's more about taking in consideration every aspect or tradeoff when choosing a technology. 

Perhaps it's more correct to use mindful http://www.dictionary.com/browse/mindful

**Comment by francesco-strazzullo** [comment]
I opened a PR to change it in "mindful". You can check it out here #22
