### ISSUE TITLE
Define scope of the proposal

### ISSUE THREAD

**Issue by francesco-strazzullo** [frameworkless-movement/manifesto#3]
this is one the questions created by @apiraino in issue #1.

**Comment by Violo** [comment]
Hi @apiraino, the frameworkless-movement manifesto scope is “software development” and every professional involved in that process. The “philosophy” of frameworkless approach involves every professional (from designers to developers) who need something for which something already exists. This approach helps professional to ask their self the right questions for a better and aware choice. 
It seems strange to talk about designers when talking about frameworkless but tools that propose something “ready” also exist in the design, and the approach to ask your self the right question is the same.
