### ISSUE TITLE
Mindful Decision

### ISSUE THREAD

**Issue by francesco-strazzullo** [frameworkless-movement/manifesto#33]
With the PR #32 we changed the principle `The choice of a framework is a technical choice and thus should be made by technical people, but to make mindful decisions business needs should be kept in consideration.` into the more concise (and better) `The choice of a framework is a technical one and should be made by technical people, taking business needs into account.` 

While I really like the new version, we lost the concept of **mindful decision**. What do you think? Should we try to rewrite the principle again or is it good enough?

**Comment by ubaldop** [comment]
My humble proposal:

`The mindful choice of a framework is a technical one and should be made by technical people, taking business needs into account.`

**Comment by xpmatteo** [comment]
Sounds good to me

**Comment by xpmatteo** [comment]
Sounds good to me

Il giorno lun 12 nov 2018 alle ore 14:28 Peter Pan <notifications@github.com>
ha scritto:

**Comment by francesco-strazzullo** [comment]
> My humble proposal:
> 
> `The mindful choice of a framework is a technical one and should be made by technical people, taking business needs into account.`

I like it, I create a PR.
