### ISSUE TITLE
Link to Awesome Frameworkless?

### ISSUE THREAD

**Issue by francesco-strazzullo** [frameworkless-movement/manifesto#35]
Given that this manifesto is our main way to communicate outside, I would like to add a link to our Awesome Frameworkless list. https://github.com/frameworkless-movement/awesome-frameworkless

I'm not sure that is a good idea, because I would like to keep this manifesto "free" of links. What do you think?

**Comment by francesco-strazzullo** [comment]
@adellava @lorenzomassacci @Violo I just created a PR that adds a link to our awesome list and to our badge. What do you think?

**Comment by lorenzomassacci** [comment]
At this moment I don't think is useful add the awesome list's link in the manifesto. The repo is already "visible" under the context of Frameworkless Movement (GitHub and website) and for me, it is enough

**Comment by francesco-strazzullo** [comment]
Ok you convinced me, we don't have a place where we show the github badge. What do you think to add the badge instructions to the awesome list?

**Comment by lorenzomassacci** [comment]
Yes, could be a good idea.

**Comment by francesco-strazzullo** [comment]
Ok I will do that later
