### ISSUE TITLE
When do guidelines for a frameworkless approach become a framework?

### ISSUE THREAD

**Issue by tlaak** [frameworkless-movement/manifesto#9]
When you start forming guidelines and practical approaches for a frameworkless application, aren't you actually creating a framework?

What's the definition of a framework and when does a set of guidelines become a framework?

**Comment by sensorario** [comment]
I think, ... reinvent just wheels you need to reinvent.
Reuse just wheels that are too old to create value today.

**Comment by francesco-strazzullo** [comment]
IMHO one of the prerequisites to work effectively with frameworkless code is to apply the [YAGNI](https://it.wikipedia.org/wiki/You_aren%27t_gonna_need_it) principle. My point is that you should just write code that solves that particular customer’s problem at that particular moment. 

If you stick to YAGNI your guidelines are not a framework, just a solution to very specific problems. The problem with this approach is that a team should fight the urge to propagate your shiny new architecture to other projects, or to other parts of the application that don't need it.

I suggest reading these two articles from Matteo Vaccari's blog about working without frameworks.

1. [Part I](http://matteo.vaccari.name/blog/archives/1019)
2. [Part II](http://matteo.vaccari.name/blog/archives/1022)

**Comment by francesco-strazzullo** [comment]
@lorenzomassacci @Violo @adellava what do you think? We should try to add something about "not creating a new framework?"

**Comment by lorenzomassacci** [comment]
I tried to explain my opinion on this issue: https://github.com/frameworkless-movement/manifesto/issues/6 (What Frameworkless is not?)

I think it could be useful add this clarification in the README. 
In the next few days, I’ll propose a PR

**Comment by francesco-strazzullo** [comment]
@tlaak we add some information about this topic with the PR #12. If you think that it's not enough just open another issue.
